name: CI - Building Docker image

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Enter Commit ID to deploy'
        required: true
        
#   push:
#     branches: 
#       - 'sprint'

  pull_request:
    branches: ["*"]
    
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm ci

      - name: Docker Build
        id: build-image
        run: |
          # Build the docker image
          docker build -t vital-cp-app-dev:latest --target base .
